# Generated by Django 6.0.1 on 2026-01-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('pk', models.CompositePrimaryKey('symbol', 'timeframe', 'candle_time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(db_index=True, max_length=10)),
                ('candle_time', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'db_table': 'ohlcv',
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-candle_time'], name='ohlcv_symbol_441d8a_idx')],
            },
        ),
    ]
