# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),  # ← замените на вашу первую миграцию
    ]

    operations = [
        # 1. Создаём гипертаблицу
        migrations.RunSQL(
            sql="""
                SELECT create_hypertable(
                    'ohlcv',
                    'candle_time',
                    chunk_time_interval => INTERVAL '7 days',
                    if_not_exists => true
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS ohlcv;",
        ),
        # 2. Включаем сжатие (экономия 70–90% места)
        migrations.RunSQL(
            sql="""
                ALTER TABLE ohlcv SET (
                    timescaledb.compress,
                    timescaledb.compress_segmentby = 'symbol, timeframe',
                    timescaledb.compress_orderby = 'candle_time DESC'
                );
            """,
            reverse_sql="ALTER TABLE ohlcv RESET (timescaledb.compress);",
        ),
        # 3. Добавляем политику автоматического сжатия (чанки старше 7 дней)
        migrations.RunSQL(
            sql="""
                SELECT add_compression_policy('ohlcv', compress_after => INTERVAL '7 days');
            """,
            reverse_sql="SELECT remove_compression_policy('ohlcv');",
        ),
        # 4. Убеждаемся, что индекс существует (для быстрого поиска по паре + таймфрейму)
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS ohlcv_symbol_timeframe_candle_time_idx
                ON ohlcv (symbol, timeframe, candle_time DESC);
            """,
            reverse_sql="DROP INDEX IF EXISTS ohlcv_symbol_timeframe_candle_time_idx;",
        ),
    ]
